In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[2,3],[6,7],[3,5]])
v = np.array([4,4])
u = np.array([5,5])
v1 = np.array([4,4,4])
u1 = np.array([5,6,7])

c = 3

#Matrix multiplication

#Matrix-vector multiplicaion (number of matrix column should be equal to vector dimension)
Av =np.dot(A,v)

#matrix-matrix multiplication (number of row of first matrix should be equal to numeber of columns of second matrix) 
#AB = np.dot(A,B)

#Matrix Addition 

AB_add = A + B


#Vector Multiplication 
vu = np.dot(v,u)

v1u1= np.cross(v1,u1) 

v1u1_hadamard = v1*u1

#Magnitude of vector

L1_norm = np.sum(np.abs(v1))
L2_norm = np.linalg.norm(v1, ord=2)
L3_norm = np.max(np.abs(u1))

print (L1_norm, ": is L1 norm")
print (L2_norm, ": is L2 norm")
print (L3_norm, ": is L3 norm")




12 : is L1 norm
6.928203230275509 : is L2 norm
7 : is L3 norm


In [3]:
#determinant of a matrix
A1 = np.array([[1,2],[3,4]])
det_a = np.linalg.det(A1)
print (det_a, ": is its determininat")

#Rank of a matrix (number of linearly independent row or column)
A2= np.array([[1,2,3,4],
              [2,4,6,7], 
              [9,5,6,7],
              [5,6,7,1]])

rank = np.linalg.matrix_rank(A2)
print ("rank of A2 is: ", rank)

#eigenvalue and eigenvector

eigenvalue, eigenvector = np.linalg.eig(A2)

print("eigenvalues are:", eigenvalue)
print("eigenvectors are:", eigenvector)

# Specteral decomposition of a matix

A3 = np.array([[1,2,3],
               [2,1,5],
               [3,5,0]])
eigenvalue, eigenvector = np.linalg.eig(A3)

print("eigenvector of A3, symmertical matrix is: ", eigenvector)

-2.0000000000000004 : is its determininat
rank of A2 is:  4
eigenvalues are: [19.18305702 -0.10364458 -1.96799679 -5.11141565]
eigenvectors are: [[-0.27173588 -0.09024246 -0.2918424  -0.34467047]
 [-0.5177485   0.77600374 -0.60301318 -0.53919341]
 [-0.64389626 -0.61631711  0.74145547  0.03831523]
 [-0.49345081  0.09913486 -0.03803819  0.7674664 ]]
eigenvector of A3, symmertical matrix is:  [[ 0.48043809  0.85577615 -0.19190214]
 [ 0.6259741  -0.48785591 -0.60840204]
 [ 0.61427654 -0.17217374  0.77007826]]


In [4]:
# Test: when you multiply a non symmetrical matrix with its transpose, you get a symmertical martix
A2= np.array([[1,2,3,4],
              [2,4,6,7], 
              [9,5,6,7],
              [5,6,7,1]])

A2_t = A2.T

sym_matrix = np.dot(A2, A2_t)

print("is it symmetrical?: ", sym_matrix)


is it symmetrical?:  [[ 30  56  65  42]
 [ 56 105 123  83]
 [ 65 123 191 124]
 [ 42  83 124 111]]


In [5]:
#Inverse of a matrix

product = np.dot(A2, np.linalg.inv(A2))

print ("identity matrix?: ", product)

identity matrix?:  [[ 1.00000000e+00  0.00000000e+00 -2.77555756e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00 -3.55271368e-15  1.00000000e+00  0.00000000e+00]
 [ 7.10542736e-15 -1.77635684e-15 -2.77555756e-17  1.00000000e+00]]


In [6]:
# Specteral Decomposition

A4 = np.array([[1,2,4],
               [2,1,3],
               [4,3,6]])

eigenvalue, eigenvector = np.linalg.eig(A4)

D = np.diag(eigenvalue)

A_decomposed = eigenvector @ D @ eigenvector.T

print ("Specteral decomposition: \n", eigenvector)

#each column in eigenvector matrix represent eigenvector associated with each eigen vector


# Singular value decomposition 

U, E, Vt = np.linalg.svd(A4)

print ("\n \nU is", U)
print ("\n E is\n", E)
print ("\n Vt is\n", Vt)


print(np.linalg.svd(A4))


Specteral decomposition: 
 [[ 0.45701098  0.88411325 -0.09738952]
 [ 0.38195407 -0.29395392 -0.87618616]
 [ 0.80327582 -0.36322837  0.47203082]]

 
U is [[-0.45701098  0.88411325 -0.09738952]
 [-0.38195407 -0.29395392 -0.87618616]
 [-0.80327582 -0.36322837  0.47203082]]

 E is
 [9.70222288 1.30832569 0.3938972 ]

 Vt is
 [[-0.45701098 -0.38195407 -0.80327582]
 [-0.88411325  0.29395392  0.36322837]
 [ 0.09738952  0.87618616 -0.47203082]]
SVDResult(U=array([[-0.45701098,  0.88411325, -0.09738952],
       [-0.38195407, -0.29395392, -0.87618616],
       [-0.80327582, -0.36322837,  0.47203082]]), S=array([9.70222288, 1.30832569, 0.3938972 ]), Vh=array([[-0.45701098, -0.38195407, -0.80327582],
       [-0.88411325,  0.29395392,  0.36322837],
       [ 0.09738952,  0.87618616, -0.47203082]]))


In [7]:
# Principle component analysis

from sklearn.decomposition import PCA

# Sample dataset
X = np.array([[1, 2, 4],
              [2, 1, 3],
              [4, 3, 6]])

# Initialize PCA with 2 components (dimensionality reduction to 2D)
pca = PCA(n_components=2)

# Fit PCA on the data
X_pca = pca.fit_transform(X)

# Print results
print("Principal Components:\n", pca.components_)
print("Explained Variance (Eigenvalues):\n", pca.explained_variance_)
print("Transformed Data (Projection onto Principal Components):\n", X_pca)

Principal Components:
 [[ 0.62165736  0.40973186  0.66757916]
 [-0.7679405   0.48670495  0.41639607]]
Explained Variance (Eigenvalues):
 [4.96119089 0.70547578]
Transformed Data (Projection onto Principal Components):
 [[-1.05140286  0.88512197]
 [-1.50705652 -0.78591954]
 [ 2.55845939 -0.09920243]]


In [8]:
import pandas as pd
df = pd.read_csv(r"C:\Users\alokd\Downloads\Telegram Desktop\debug_book.csv")
df.head()

timestamp  bid_price_0  bid_size_0  ask_price_0   
0  2024-08-09 00:04:28.460346         0.49     30862.4          0.5  \
1  2024-08-09 00:04:28.557399         0.49     31462.4          0.5   
2  2024-08-09 00:04:47.458957         0.49     30862.4          0.5   
3  2024-08-09 00:04:47.558336         0.49     31462.4          0.5   
4  2024-08-09 00:19:27.505261         0.49     30862.4          0.5   

   ask_size_0  bid_price_1  bid_size_1  ask_price_1  ask_size_1  bid_price_2   
0     24384.6         0.48    117105.0         0.51     25382.0         0.47  \
1     24384.6         0.48    117105.0         0.51     25382.0         0.47   
2     24384.6         0.48    117105.0         0.51     25382.0         0.47   
3     24384.6         0.48    117105.0         0.51     25382.0         0.47   
4     24384.6         0.48    117105.0         0.51     25382.0         0.47   

   ...  ask_price_2  ask_size_2  bid_price_3  bid_size_3  ask_price_3   
0  ...         0.53      1400.0         0.46     11642.0         0.54  \
1  ...         0.53      1400.0         0.46     11642.0         0.54   
2  ...         0.53      1400.0         0.46     11642.0         0.54   
3  ...         0.53      1400.0         0.46     11642.0         0.54   
4  ...         0.53      1400.0         0.46     11642.0         0.54   

   ask_size_3  bid_price_4  bid_size_4  ask_price_4  ask_size_4  
0      2800.0         0.45     14606.8         0.55       48.88  
1      2800.0         0.45     14606.8         0.55       48.88  
2      2800.0         0.45     14606.8         0.55       48.88  
3      2800.0         0.45     14606.8         0.55       48.88  
4      2800.0         0.45     14606.8         0.55       48.88  

[5 rows x 21 columns]

In [9]:
matrix = df.drop("timestamp",axis=1).values
matrix

array([[4.90000e-01, 3.08624e+04, 5.00000e-01, ..., 1.46068e+04,
        5.50000e-01, 4.88800e+01],
       [4.90000e-01, 3.14624e+04, 5.00000e-01, ..., 1.46068e+04,
        5.50000e-01, 4.88800e+01],
       [4.90000e-01, 3.08624e+04, 5.00000e-01, ..., 1.46068e+04,
        5.50000e-01, 4.88800e+01],
       ...,
       [5.10000e-01, 1.01648e+04, 5.20000e-01, ..., 7.29176e+03,
        5.60000e-01, 2.10000e+04],
       [5.10000e-01, 9.86477e+03, 5.20000e-01, ..., 7.29176e+03,
        5.60000e-01, 2.10000e+04],
       [5.10000e-01, 9.86477e+03, 5.20000e-01, ..., 7.29176e+03,
        5.60000e-01, 2.10000e+04]])

In [10]:
pca = PCA(n_components=4)

df_pca = pca.fit_transform(matrix)

print("Transformed Data (Projection onto Principal Components):\n", df_pca)


Transformed Data (Projection onto Principal Components):
 [[ 56454.27434389  49804.61437628 -35781.37350664 -16868.60567361]
 [ 56480.64479702  49833.54183791 -35935.594534   -16423.71993644]
 [ 56454.27434389  49804.61437628 -35781.37350664 -16868.60567361]
 ...
 [-21495.28989666  20657.15435546  -2386.95254991 -20769.74034508]
 [-21508.47644174  20642.68917826  -2309.83432518 -20992.20545795]
 [-21654.70067568  20686.5101989   -2553.86408109 -21068.55376646]]
